config/routes.rb
Go::Application.routes.draw do

  resource :chat do 
    post 'send_data'
  end

  resources :posts
  match "/users.json" => 'chats#users'

  match "/mustache_templates.js" => MustacheCacher

  root :to => "chats#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates_associated :user
  validates :chat_input, :presence => true
end

app/models/user.rb
class User < TwitterAuth::GenericUser
  # Extend and define your user model as you see fit.
  # All of the authentication logic is handled by the 
  # parent TwitterAuth::GenericUser class.
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_filter :login_required
  protect_from_forgery :except => :post
  respond_to :json
  include ApplicationHelper
  delegate :link_to, :auto_link, :sanitize, :to => 'ActionController::Base.helpers'

  def index
   @posts = Post.order('created_at DESC')
  end
  
  def users
    @users = User.select([:id, :name]).where("name like ?", "%#{params[:q]}%")
    respond_to do |format|
      format.json { render :json => @users.map(&:attributes) }
    end
  end
  
  def send_data
    msg = sanitize(
            auto_link(
              auto_image(
                auto_mention(params[:chat_input])
              ), :html => { :target => '_blank' }
            ), :tags => %w(a img mark), :attributes => %w(href src alt target)
          )
    @post = current_user.posts.create!(:chat_input => msg)
    post_data = {
      :command           => :broadcast,
      :body              => msg,
      :name              => current_user.name,
      :profile_image_url => current_user.profile_image_url,
      :twitter_login     => current_user.login,
      :type              => :to_channels_without_signature, 
      :channels          => 'groupon_go'
    }
    Pusher['groupon_go'].trigger!('new_post', post_data)
    #render :juggernaut => {:type => :send_to_channels, :channels => ['web']} do |page|
    #  page.insert_html :top, 'chat_data', "<li>#{h params[:chat_input]}</li>"
    #end
    render :nothing => true
  end
  
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  before_filter :login_required
  def index
    @posts = Post.all.order(:created_at)
  end

  def post
    #Juggernaut.send_to_channels_without_sign(params[:chat_input], ['iphone'])
    #
    #render :juggernaut => {:type => :send_to_channels, :channels => ['web']} do |page|
    #  page.insert_html :top, 'chat_data', "<li>#{h params[:chat_input]}</li>"
    #end
    #render :nothing => true
    @post = Post.create(params[:post])
    #Pusher['groupon_go'].trigger!('post', {:post => params[:post]})
    redirect_to :controller => :chat, :action => :send_date, :post => @post
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def auto_image msg
    unless msg.blank?
      img_url = /(^https?:\/\/(?:[a-z\-]+\.)+[a-z]{2,6}(?:\/[^\/#?]+)+\.(?:jpe?g|gif|png))/
      msg.gsub img_url, link_to('<img src="\\1" alt="image" />'.html_safe, '\\1', :target => "_blank")
    end
  end
  
  def auto_mention msg
    unless msg.blank?
      login = /(@[\S]+)/
      msg.gsub login, '<mark>\\1</mark>'
    end
  end
end

app/views/chats/index.html.haml
#container

  #intro 
    %h1
      Welcome to Groupon Go -- we're hacking on a real-time chat app in realtime, for real. 
    %p
      The project itself is 
      = link_to("on Github","https://github.com/groupon/chat") 
      and we've got a backlog going in 
      = link_to("Pivotal Tracker.","https://www.pivotaltracker.com/projects/270327")
      Feel free to grab stories and send pull requests—we'll be merging and redeploying all day.

  #type_wrapper
    - form_tag send_data_chat_path(:format => :json), :id => 'message_post_form' do
      = text_field_tag :chat_input, '', :placeholder => "#{current_user.name}: "
      = submit_tag 'Post'
      %span.error
        You can't submit an empty message!
      %span.loading
      %ul#reply
      
  %ul#chat_data
    - @posts.each do |post|
      = raw Mustache.render(File.read('./app/views/chats/_post.html.mustache'), {:profile_image_url => post.user.profile_image_url,:twitter_login => post.user.login, :name => post.user.name, :chat_input => post.chat_input, :time_ago => time_ago_in_words(post.created_at)})

app/views/layouts/application.html.haml
!!! 5
%head
  %title 
    Groupon Go
  %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" }
  = stylesheet_link_tag 'mobile', :media => 'all and (max-width: 480px)'
  = stylesheet_link_tag 'screen', :media => 'all and (min-width: 481px)'
  = javascript_include_tag 'jquery', 'pusher', 'mustache', '/mustache_templates.js', 'application'
%body
  = yield